# Generated by Django 4.1.2 on 2022-11-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiTra', '0007_alter_cardioexercises_cardioworkout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardioexercises',
            old_name='cardioWorkout',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='weightexercises',
            old_name='weightWorkout',
            new_name='workout',
        ),
    ]
